{{- if .Values.apiKeySecret.create }}
{{- if not .Values.log10xApiKey }}
{{- fail "log10xApiKey must be set to a valid API key when apiKeySecret.create is true." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "log10x-cron.fullname" . }}-api-key
  labels:
    {{- include "log10x-cron.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.apiKeySecret.secretKey }}: {{ .Values.log10xApiKey | b64enc | quote }}
{{- end }}